### ISSUE TITLE
Abstract

### ISSUE THREAD

**Issue by ratnanil** [MicheleSenn/Projectwork#2]
https://github.com/MicheleSenn/Projectwork/blob/d3fa112981d11eb59704455b19f87302a7b25d93/README.md?plain=1#L13-L15

> This project aims at modelling the behavior or wild boars after scare-off measures. It is hypothesized that they will return rather quickly back to the scare-off location and this returning pattern will be analysed. Additionally, the individuals are expected to communicate with each other and influence their time of returning, which will also be conceptualized in this project.

- How do you decide which wild boar you will analyse for a specific scare of measure?
- How do you define "return" and "rather quickly"?
- How do you determine whether the animals communicate with each other and influence their time of returning? How do you conceptualize this?

**Comment by Lianikus** [comment]
Notes from the coaching session:
- First, we would need to analyse which wild boar is influenced by which scare off measure by comparing distances to the Schreck.
- Return: show when the boars are in a defined area around the Schreck and when not (boolean)
- Communication might be too much to analyse or not feasible as they move mostly alone.
