### ISSUE TITLE
Research Questions

### ISSUE THREAD

**Issue by ratnanil** [MicheleSenn/Projectwork#3]
https://github.com/MicheleSenn/Projectwork/blob/d3fa112981d11eb59704455b19f87302a7b25d93/README.md?plain=1#L17-L22

> Once a scare-off measure has proven to have an effect and cause the wild boars to relocate, it needs to be examined how long the effect lasts. Therefore, the two following research questions were formulated:
> 1. How can the long-term effects of scare-off measures be modelled?
> 2. Can a trend of returning to the scare-off location be detected or even conceptualized?

I think these research questions are too ambitious..

**Comment by Lianikus** [comment]
Notes from the coaching:
We mostly keep on working on the topic of conceptualizing RETURNING. Much more will be too much.
