### ISSUE TITLE
Results / products

### ISSUE THREAD

**Issue by ratnanil** [MicheleSenn/Projectwork#4]
https://github.com/MicheleSenn/Projectwork/blob/d3fa112981d11eb59704455b19f87302a7b25d93/README.md?plain=1#L24-L37

> We expect a quick return to the scare-off-location, e.g. withing a few days or maximum weeks if the measures are not repeated.

I'm not sure if it is reasonable to analyse movement patterns more than a few days after the measure

> It might be interesting to build a time series of returning animals after the measures

What do you mean by "building a time series"?

> and also looking at what time of day the dare returning most.

I think this would require a very clear definition of what "returning" means, and I'm not sure if this is reasonable

> 2. We expect some kind of social behavior, e.g. meeting of and communication between individuals.

You expect the animals to meet specifically after the wildschwein schrek were on? Why would they meet only afterwards, but not before? What if you don't find such meeting patterns?

> Result: Model meeting patterns, maybe followed by an analysis of lead-and-follow or flocking patterns.

- How high is the sampling rate of the wildboar locations? How high would you need it to be to determine reasonable lead follow patterns?
- how is flocking different to meeting in this context? would you expect multiple individuals to flock?

> 3. We are interested if there are differences between the animals' natures such as very courageous vs. very fearful individuals.

Wouldn't this need multiple experiments (scare off measures) per animal?

> Option 2: Relating biology to their behavior (influences such as mating season, etc.)

Again: I'm not sure your sample sice will suffice

**Comment by Lianikus** [comment]
Notes from the coaching:
- Data structure doesn't allow for most of our points, so we can omit them.
- Focus more on time of day, weather influence, do they come back shortly after or not
