### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by ratnanil** [MicheleSenn/Projectwork#5]
https://github.com/MicheleSenn/Projectwork/blob/d3fa112981d11eb59704455b19f87302a7b25d93/README.md?plain=1#L39-L45

> Long-term data for movement trajectories will be necessary (at least 6 weeks). 

see https://computationalmovementanalysis.github.io/ComputationalMovementAnalysisData/articles/Spatiotemporal-Overlaps.html

> Data should be of different times of day and of several individuals in a similar location --> we need to find these sources. 

see https://computationalmovementanalysis.github.io/ComputationalMovementAnalysisData/articles/Spatiotemporal-Overlaps.html

> Furthermore, mapdata will be needed, which can be aquired from open sources. 

which sources are you thinking of? See also: https://computationalmovementanalysis.github.io/W5_3_tasks_and_inputs.html#tasks-and-inputs-3

> Weather data would help to put the visualiziations into context and would help for a better interpretation. This could be acquired from open sources. 

Very very challenging. What sources are you thinking of?

 > Some background information on the boars social behavior and seasonal movements would also be interesting and help for a better understanding of the data. It could be difficult to get that data though. 

see https://computationalmovementanalysis.github.io/ComputationalMovementAnalysisData/reference/wildschwein_metadata.html

**Comment by Lianikus** [comment]
Thanks for the links!
Notes from the coaching:
- Weather sources: We could include the nearest available weather station, if possible and match weather attributes on the timestamp (not perfect in a real study, ok for the semester project).
