### ISSUE TITLE
Analytical concepts 

### ISSUE THREAD

**Issue by ratnanil** [MicheleSenn/Projectwork#6]
https://github.com/MicheleSenn/Projectwork/blob/d3fa112981d11eb59704455b19f87302a7b25d93/README.md?plain=1#L47-L54

> Calculating distances to Scare-Off-Location over time (-> e.g. Visualisation as timecube)

How are you thinking of calculating these *precisely*?

> Segmentation with Euclidean distance

What do you mean by this?

> Meetings between animals on temporally close observations

I feel like these meeting patterns don't really match the first research question

> (Small  multiples of) trajectories or locations comparing seasons, time of day or individuals

What do you mean by this?

**Comment by Lianikus** [comment]
Notes from coaching:
- After EDA and finding which individual is Schrecked by what, focus on returning pattern by building a "In the Field / not in the Field" vs. distance to Schreck graph
