### ISSUE TITLE
Correct URL?

### ISSUE THREAD

**Issue by ratnanil** [MicheleSenn/Projectwork#7]
Hey Michele!

Nice to see that you have managed to work with RMarkdown and github pages quite smoothly! Just a quick question: which URL points to the correct version of your Report?

https://michelesenn.github.io/Projectwork/Semesterproject.html or
https://michelesenn.github.io/Projectwork/Semesterproject_slimversion3.html

**Comment by Lianikus** [comment]
Hi Nils. It's the second one --> slimversion3. We had some issues when working on it together and merging didn't work so we had to create new versions... but other than that, I agree that we managed the GitHub well :)
